import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "./sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Sidebar />
      <body className="font-lora flex-1">{children}</body>
    </html>
  );
}
